### ISSUE TITLE
shape_iris_2024 Ingestion fail

### ISSUE THREAD

**Issue by aloysius-tim** [make-open-data/make-open-data#115]
Impossible d'ingérer shape_iris_2024, le py script est killed après quelques minutes sans plus de détail.

Peut être un problème de ma version de PG (pg 14) ?

**Comment by soufianekhoudmi** [comment]
L'ingestion de shapes utilise shp2pgsql
Tu peux vérifier que tu l'as avec  `which shp2pgsql`

Je viens de voir que ce n'est pas necessairement livré avec Postgis ou du moins pas toutes les versions
Peut-être installer manuellement shp2pgsql ou up Postgis ?

https://gis.stackexchange.com/questions/148524/i-have-not-found-shp2pgsql-in-postgis-installation
https://gis.stackexchange.com/questions/384381/shp2pgsql-available-in-postgis13-3-1-alpine-but-no-in-postgis13-3-1-docker-ima

**Comment by aloysius-tim** [comment]
Yes il est bien présent, je continue a essayer de debug..

**Comment by soufianekhoudmi** [comment]
Si tu es sur Windows, peut-être que ça vient de la définition des paths.

**Comment by aloysius-tim** [comment]
Ça semble venir d'un manque de puissance de ma machine (Ubuntu 4Cores 8Gb ram). C'est Kill dés que la machine s'approche des 100% de CPU..
Je suis sous mac normalement aussi, mais connection internet trop mauvaise pour bosser avec des gros fichiers

J'ai cependant réussi à les ingérer avec FIONA qui est installed by default (dep de geopandas je pense)

**Comment by soufianekhoudmi** [comment]
D'où la volonté d'installer pg_duckdb pour lire directement des S3.
https://github.com/duckdb/pg_duckdb?tab=readme-ov-file#features

Mais ça fait installer une extension pas encore supportée par la pluspart des PG managée

Je te laisse fermer ce ticket si tu estimes qu'il n'ya pas grande chose à faire.

**Comment by aloysius-tim** [comment]
J'ai fait une proposition de PR avec FIONA pour streamer le shapefile

https://github.com/make-open-data/make-open-data/pull/117

**Comment by soufianekhoudmi** [comment]
Ah je n'avais pas vu que tu avais ouvert une PR. Du coup je réouvre cette issue :)

**Comment by soufianekhoudmi** [comment]
Tu peux essayer l'option chuckzier de geopandas.to_postgis() ?
