### ISSUE TITLE
404 quand on clique sue "Accueil" sur le site publique de Make Open Data

### ISSUE THREAD

**Issue by frague59** [make-open-data/make-open-data#169]
Bonjour,

J'ai constaté une belle 404 quand on clique sur le lien "Accueil' en haut à droite de la page d'accueil du site publique.

Cordialement,

**Comment by soufianekhoudmi** [comment]
Merci pour le retour

C'est réparé ... Le lien "Accueil" renvoi vers la page en soit, donc ne sert pas à grand chose mais je l'ai laissé comme c'est fait la référence en MKdocs https://squidfunk.github.io/mkdocs-material/ 

La homepage est un overides de MKdocs

:)
