### ISSUE TITLE
Documenter les modèles Code Officiel Géographiques

### ISSUE THREAD

**Issue by soufianekhoudmi** [make-open-data/make-open-data#32]
En tant qu'utilisateur, je veux pouvoir comprendre les tables COG à partir du catalogue https://data.make-open-data.fr/#!/overview

DoD : models/geo/schema avec : 
- description des tables résultantes (généralement en commentaire des modèles)
- description des colonnes
- remontée des éventuels problèmes

**Comment by cwaihai** [comment]
je m'en occupe

**Comment by soufianekhoudmi** [comment]
Done
